language: php
php:
- '7.4'
before_script:
- composer self-update
- composer install --no-interaction
- cp .env.travis .env
script:
- vendor/bin/phpunit
deploy:
  provider: heroku
  app: quiet-coast-59009
  run: php artisan migrate --seed --force
  on:
    branch: master
  api_key:
    secure: GOGqEdKrx9iK1HG8f9XsFdjWJpwFv7wxm90Xgkt8LkyExn7d6Ghw63R4Al5NykAifaHLdfTCjkffzopqpOBhwJM9DlU2JtrU0Cvm4JDi73Gp5vOnik09iSSu6lOduSJA39PgRA+igQ5plzB3DQ0rS+blIFJGA9i2W60H4H1GyV5nKkDDMtkjMxTAKfeXYNdsmWhotgK1LAfEKZ8/iVqxWxli/7Wjn/OodLWXF8Nnd2fTRJNO5VFbpgbRLG004rXRCOlD7tlam+rtoDz+9jw0E95Q1+ihcofveMmTvTcT5jLe3ML36FQ0gDA8YjkUeErEYUdqaNKnxRkbkD1msc9Onu7UIqJWHp0RMh+sP28zfwYj5re41Tdi/8yJOGVtstCKcJaRiKWK7G+SKoI46BIT5K6niAY1dIJ/wYTZOo5Uope9XfPGz1TvoycVG2VHncJu7raxCzvp+X8OTvQ+upJAeIRO0oFR2txv+fF5s9vOdCjIB5HPQz0BuwF2jJ2hAAsbUJ9qiCMNt5lCtNiZlnWnxp5EtZzbcgyugVuwPepdC1UZDX+s46i7yHI5cAmPUhzHi4pO99ercMF9z/+LWkI70sf20rkg4InzPNVY0hQxGwYvbJajb1t6uuS0ylxGFfO9FaPAp/NaY3DlyHF5+wfiBUAczN0xZ85QwJai8mkwxck=
