language: php
php:
- '7.4'
before_script:
- composer self-update
- composer install --no-interaction
- cp .env.travis .env
script:
- vendor/bin/phpunit
deploy:
  provider: heroku
  edge: true
  skip_cleanup: true
  app: quiet-coast-59009
  on:
    branch: master
  api_key:
    secure: fnHDb1NWg86sT8Q+G2/9HOTaA0EdZrEbOV/d0mveVwVaRXsi1LQAfO5G79HxOdXRWye7BTWDmgVcJPYgQF3+Qh6J6MLg3Ws9DlZ46mGg3bqXJ90Amm4548gJ30OkVJ8ZsblMIIc18eIAYouBYXcRSdOoJsgJVcBe5hBkAXad3IoXdcTheAykbZLE68Fg0lBfSgJSt0DEDAi74sOcSmN0CUtXUkYWzS83ZsHcEROp64cFZ9UE4JP66PeI3N1CXRyAIR1Y9RGF7/hkD407laeOZrIVWe4EnfA0np0mEs+1iS3XqtoxwxKWQ/4PFddXbDML5BSw3fQ54ZyxBJq9ix7GjYMDcK6aotdnrYpTZID7Yu0VM0VOug52ImbzReuDejlj4KarwiCrgFDTAGW6uqWSteFB3ZmICKLR3U3kbqyOzchx3xc+opb3A4JBj+Bk71Zfx2MKaiAO3szXhiRQJA0vDVRlPSddu6URt3UV41iYLSDSpOop6CcCgGYfMYNiEuquJ+Ws9n21QhyKA+aPt3jLvC6B7TY3Z6tSbUvjqKiZnXdU9SBCti/i4OksGTeEmQ+EkI0FpEWOkjsm+XxlOjwEGjdPIYs63KPqfWrGyt69rxKL14n5ZaZyU2F0/7eAGhzgNeaFDFJ363i5PLc+/XDuLnn3dZ23sxOiE//5c/jzExA=
  run: php artisan migrate --seed --force
