language: php
php:
- '7.4'
before_script:
- composer self-update
- composer install --no-interaction
- cp .env.travis .env
script:
- vendor/bin/phpunit
deploy:
  provider: heroku
  app: quiet-coast-59009
  run: php artisan migrate --seed --force
  on:
    branch: master
dd:
  secure: owVh7W+wenE8buycf4v2qTwlde3GXGY494/EHcsgYtF507caEbgPgbhW9F/WwUnM1sUvbjA23TEps1I4a5LYGWwPSYgBszhJJl1HzHbZRmMNpkx5la0eHMmTtAGpDy1elltXtFhUPFGsRRyk/qnDrpjkaYTo0Ipc38mKo5F3oKHISB8OigSTBj3SX2Fu9CGGFkO95tBvilMqBV2M383ga8HojIyxnnUxoToKCxI/e+SJQUKqyZh+ZBnpFoy/hc4/o9h7bH+utITwjiqhR+BR5esyVkjQW3/VOMghFRxGD/E+Ziok0BwbrKYWSsqji2/UldXbip27gEPL3j43yn2jGVoX3qyOZr4Xwd5Z0vKPY+MsYACMGCcFbhMnHAgXCctrOEyN1DOIA2uF6fLwi/MS42fac1cN2L5PWnel2IBuJQW9wQEUVZsbTZeFWoNrzbLs9y3OwXQFKiOxht6qeNWACnLAhou6bSd7GPwk4DUJ7Z+yNpcxEBBm9PWNBt3CEFYKUizHB6HXpP/+VC9hA+8srgqQmw7vZivoGN03Gm2RV66jMN0B8rSyLXJ7zkvKuA0OM1V6VsocIY8hmZ0oUU2XpS63pGSZXLzM1BnazBdTs0/qtoKgVxb7msDXf9C9A2yvcxWrREhgihZE5isFqJeO4S3KChxlCCKIRwwlE7vG4Bg=
