language: php
php:
- '7.4'
before_script:
- composer self-update
- composer install --no-interaction
- cp .env.travis .env
script:
- vendor/bin/phpunit
deploy:
  provider: heroku
  app: quiet-coast-59009
  run: php artisan migrate --seed --force
  on:
    branch: master
