language: php
php:
- '7.4'
before_script:
- composer self-update
- composer install --no-interaction
- cp .env.travis .env
script:
- vendor/bin/phpunit
deploy:
  provider: heroku
  api_key:
    secure: SdJ8S2TTMTmdXwqnu+FlDA16QX28Ma5N/3oD6NqIRjvyhcw/VqAeUCd9ZzmU+823yIuZHQDrKF+Sh4dm2k5X0pTDwOEjxsl+eMXrtmYhJc8YaxoTgKfEcXJBO0mytZbeeEvgUbW1sR4nfOy4rMt94dZJJ89chDWjGp5m3xbjgsd3sO7FwgbxiMvYDrLcsiWEK0n4N7k/N6HRMKFk8y79KT8lac/V8rbJBy0nVKNO5MfRlOfRgwWmuB+tIDlXbgS99aZvK/2xC23L8TfioLijSzw0Kwf/MpmssuyDze8lOdkUUO/KVApMjPtDg5oTTBJUHXS5zpJ5s9/mTWjoA/ZnYNGvMNciNjSo45NTYfk6ONm59u+MTx0ShL6qx7sKCY2zqbaDV7PqCIoP+HnWZsxbYHiauQpU9X/UAp+enrLlASOqIr8V3NgdNPlmDt/GF5qqi0OO6V66tIwjyIIvYJBuUa76fi/IjKvNWKgXgLd3949znGXTUXEe1sev1mLhUUJF9AiozxCvA5+HH1KIA0fD7ChjSKAYwmvfUZWKsJjkKEhIsjTrWCZk6l+YXTTqTatRNsWmq1qodBjfFSZ3fFPoxaoabL4nAHTB52MkONqHhOLjlzg2VQFGwu1SVfkPf2YkjJg3/xyBKn2kO1w2QuOl8y2nnUkssmDjyMgUHbo+ZpI=
  app: quiet-coast-59009
  on:
    repo: IsmaelHartmann/ProjectIsma
  skip_cleanup: 'true'
