language: php
php:
- '7.4'
before_script:
- composer self-update
- composer install --no-interaction
- cp .env.travis .env
script:
- vendor/bin/phpunit
deploy:
  provider: heroku
  app: quiet-coast-59009
  run: php artisan migrate --seed --force
  on:
    branch: master
  api_key:
    secure: PrgjHTG6rQbiRt7sO2BgmDIVVzZWWNeWOfcQzF5M5vZUoYPxFiSuHhPRqxU0EKSHHtPJ5UT4Qz9cvHpAEEEv1suD58De0MWcivan85qVV+8GSVs/XlRLAeM2xRvTlpe/nNlSMECDzxgoSmlO1yfa2rfK29nJmruzlLoYzU5GpEonHyAyhZk5yfrYdEcVJJrwWiu1gFNMniAXw/MjnkymXGigt0wGKDCYNr5V8P4n5ZMAmh3AmpocAq7G1kqFn/f4gqoZuwf+aqgWFkZUjF41PnPAgfy0w63VA/UpELbWCsZ4Fd+zO+Bh1zueTeEWXYgMtrq6TebVEk7OD63CjtJyblMjvWZ6YXfFXhDMfmldKrGaDSI3p6HNUcivITn0dlQ30H86zOmIt0XLfa5vAAaDJGqWSDwkSUBKe+jkiNJbCqnC5a1mo7cRrL1xhMxE+iR1fwEdBmFXTpPSvzN4gAz7UN9gHO74sCKxJ5iT1+ZQj+8qhaCKClxSzOnqpeZOHWr3+A5B1SP1QsDrtln9lx5GQ0K+kd+D95zSH6KtItcxApKLbaRu+GMs2Er5Mp+K76lBvw6C5QIPyFbhGNHCC454kTMN7JMK3ZgsUDWb+Wk6OGydn0dJU3bWfRBBSW5mlTXDvXGENXNZ+Sv7iDkqIDd/m8yg8yotg2GYdmOWtD+nur0=
dd:
  secure: cK47lHfGi4f8JRXXpyL/WgLc2T4WGMrQMtPGg5PfF7f2TxDae5oHy0koNJfHlaIVxoNPHC/dsG6TJkxn820oGg3IAwAJ5VjuxrfjS9vzlX9L6Tdd6cP3IqrMXo68g9ldLJJb7zFsBRuF7LjYVji0FnHifn1O38SDENava5o/NYYF2NNbKztyjLpWtWiZlehtcqXZ3JvS3qsbUjZj/OWWPbo2N1CM9wGII60FVOv89ObQNbeFjHC3fFmDgk4b8F+avE+qYN30Pyv+Dt0rSCqDf5sFwZ42dqcTpqkTvRZwb3WH8X3cO/DQ3GiknXTl2QsFVucN+l4Ra4TjBqaWpoXaWnEmWF4FAHGAUOjrCom2ALAJhlpBlWz/KjaxRR+QYB5++iegVhDlw3UMhSO+PEt/PshUBzR990ggJDMUXSExUzE+WIlyZM4S99k57mSag1oPw3mbyD+cKc0of23tlvGOq3AMIakfvZ3p4j/6DoiOiK24hGbe6GIZTccZ1qYfKrLvjYJHNsjK33uKCfrw7qb3TuJjiDqZwU4ITtRDGxPVCzQl0/B0MXH6kIXirULCBJOGGcbeNSGaJax9qqYxH3tTnGOr7xgEgdDBLW/oid0yqthqiMn3QfeGg2AcmIwkizSqsf7e7H8Nd1j0FOwrgPE22R6rPY6H2905h+5Eta3IiZU=
